class CreateEcolIncomingRecords < ActiveRecord::Migration
  def change
    create_table :ecol_incoming_records, {:sequence_start_value => '1 cache 20 order increment by 1'} do |t|
      t.integer :incoming_file_record_id, :comment => "the foreign key to the incoming_files table" 
      t.string  :file_name, :limit => 100, :comment => "the name of the incoming_file"      
      t.string  :customer_code, :limit => 20, :comment => "the unique code for the customer"
      t.string  :remitter_code, :limit => 20, :comment => "the unique code for remitter"
      t.string  :customer_subcode, :limit => 20, :comment => "the subcode for the customer"
      t.string  :invoice_no, :limit => 20, :comment => "the number or the invoice which has to be paid"
      t.string  :customer_account_no, :limit => 20, :comment => "the account number of the customer"
      t.string  :customer_subcode_email, :limit => 100, :comment => "the email id of the customer"
      t.string  :customer_subcode_mobile, :limit => 10, :comment => "the mobile no of the customer"
      t.string  :rmtr_name, :limit => 255,:comment => "the text for the single debit that is done to the employees account"
      t.string  :rmtr_address, :limit => 100, :comment => "the address of the remitter"
      t.string  :rmtr_email, :limit => 50, :comment => "the email id of the remitter"
      t.string  :rmtr_mobile, :limit => 50, :comment => "the mobile no of the remitter"
      t.number  :invoice_amt, :comment => "the total amount which has to be paid for invoice"
      t.number  :min_credit_amt, :comment => "the minimum credit amount, if the customer wants to validate for the certain range"
      t.number  :max_credit_amt, :comment => "the maximum credit amount, if the customer wants to validate for the certain range"         
      t.datetime  :start_date, :comment => "the start date of the invoice no"
      t.datetime  :due_date, :comment => "the due date for the invoice no to be paid"
      t.integer  :due_date_tol_days, :comment => "no of due days for the invoice no to be paid"         
      t.string  :rmtr_acct_no, :limit => 50, :comment => "the account no of the remitter"
      t.string  :misc_field_11, :limit => 255, :comment => "the custom attributes"
      t.string  :misc_field_12, :limit => 255, :comment => "the custom attributes"
      t.string  :misc_field_13, :limit => 255, :comment => "the custom attributes"
      t.string  :misc_field_14, :limit => 255, :comment => "the custom attributes"    
      t.string  :misc_field_15, :limit => 255, :comment => "the custom attributes"
      t.string  :misc_field_16, :limit => 255, :comment => "the custom attributes"
      t.string  :misc_field_17, :limit => 255, :comment => "the custom attributes"
      t.string  :misc_field_18, :limit => 255, :comment => "the custom attributes"       
      t.string  :misc_field_19, :limit => 255, :comment => "the custom attributes"
      t.string  :misc_field_20, :limit => 255, :comment => "the custom attributes"
      t.string  :branch_office_region, :limit => 100, :comment => "the region of the branch office"
      t.string  :sales_office_region, :limit => 100, :comment => "the region of the sales office"
      t.string  :regional_code, :limit => 50, :comment => "the code for the region of the sales office" 
      t.string  :branch_code, :limit => 50, :comment => "the code for the branch"
      t.string  :project_name, :limit => 50, :comment => "the name of the project"
      t.string  :project_code, :limit => 50,:comment => "the code for the project"                      
      t.string  :value_variation, :limit => 20, :comment => "the invoice amount tolerance percentage"                      
      t.index([:incoming_file_record_id,:file_name], :unique => true, :name => 'ecol_incoming_records_01')
    end
  end
end